/* eslint-disable @typescript-eslint/no-unused-vars */
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AppTheme from "@/components/AppTheme";
import { AppProvider } from "./context/AppContext";
import ReactQuery from "@/components/ReactQuery";
import { Session } from "next-auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
  
}: Readonly<{
  children: React.ReactNode;
  session: Session | null | undefined;  
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-screen w-screen antialiased`}
      >
        <ReactQuery>
          <AppProvider>
            <AppTheme title="Belajar ku">{children}</AppTheme>
          </AppProvider>
        </ReactQuery>
      </body>
    </html>
  );
}
